// Mocks generated by Mockito 5.4.4 from annotations
// in simple_webdav_client/test/unit_test/std_test/framework_test/client_dispatcher_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:simple_webdav_client/src/_std/lock.dart' as _i9;
import 'package:simple_webdav_client/src/_std/prop.dart' as _i10;
import 'package:simple_webdav_client/src/_std/propfind.dart' as _i3;
import 'package:simple_webdav_client/src/_std/proppatch.dart' as _i8;
import 'package:simple_webdav_client/src/namespace.dart' as _i6;
import 'package:simple_webdav_client/src/utils.dart' as _i7;
import 'package:xml/xml.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientRequest_1 extends _i1.SmartFake
    implements _i2.HttpClientRequest {
  _FakeHttpClientRequest_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PropfindRequestProp].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropfindRequestProp extends _i1.Mock
    implements _i3.PropfindRequestProp {
  MockPropfindRequestProp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  void toXml(
    _i5.XmlBuilder? context,
    _i6.NamespaceManager? nsmgr,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toXml,
          [
            context,
            nsmgr,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProppatchRequestProp].
///
/// See the documentation for Mockito's code generation for more information.
class MockProppatchRequestProp<V extends _i7.ToXmlCapable> extends _i1.Mock
    implements _i8.ProppatchRequestProp<V> {
  MockProppatchRequestProp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i8.ProppatchRequestOp get op => (super.noSuchMethod(
        Invocation.getter(#op),
        returnValue: _i8.ProppatchRequestOp.set,
      ) as _i8.ProppatchRequestOp);

  @override
  void toXml(
    _i5.XmlBuilder? context,
    _i6.NamespaceManager? nsmgr,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toXml,
          [
            context,
            nsmgr,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LockInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLockInfo<O extends _i7.ToXmlCapable> extends _i1.Mock
    implements _i9.LockInfo<O> {
  MockLockInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.LockScope get lockScope => (super.noSuchMethod(
        Invocation.getter(#lockScope),
        returnValue: _i10.LockScope.exclusive,
      ) as _i10.LockScope);

  @override
  void toXml(
    _i5.XmlBuilder? context,
    _i6.NamespaceManager? nsmgr,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toXml,
          [
            context,
            nsmgr,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get idleTimeout => (super.noSuchMethod(
        Invocation.getter(#idleTimeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#idleTimeout),
        ),
      ) as Duration);

  @override
  set idleTimeout(Duration? _idleTimeout) => super.noSuchMethod(
        Invocation.setter(
          #idleTimeout,
          _idleTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionTimeout(Duration? _connectionTimeout) => super.noSuchMethod(
        Invocation.setter(
          #connectionTimeout,
          _connectionTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set maxConnectionsPerHost(int? _maxConnectionsPerHost) => super.noSuchMethod(
        Invocation.setter(
          #maxConnectionsPerHost,
          _maxConnectionsPerHost,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get autoUncompress => (super.noSuchMethod(
        Invocation.getter(#autoUncompress),
        returnValue: false,
      ) as bool);

  @override
  set autoUncompress(bool? _autoUncompress) => super.noSuchMethod(
        Invocation.setter(
          #autoUncompress,
          _autoUncompress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userAgent(String? _userAgent) => super.noSuchMethod(
        Invocation.setter(
          #userAgent,
          _userAgent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticate(
          _i11.Future<bool> Function(
            Uri,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticate,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
          _i11.Future<_i2.ConnectionTask<_i2.Socket>> Function(
            Uri,
            String?,
            int?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectionFactory,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
        Invocation.setter(
          #findProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticateProxy(
          _i11.Future<bool> Function(
            String,
            int,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticateProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set badCertificateCallback(
          bool Function(
            _i2.X509Certificate,
            String,
            int,
          )? callback) =>
      super.noSuchMethod(
        Invocation.setter(
          #badCertificateCallback,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
        Invocation.setter(
          #keyLog,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<_i2.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [
            method,
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #open,
            [
              method,
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> openUrl(
    String? method,
    Uri? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [
            method,
            url,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #openUrl,
            [
              method,
              url,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #get,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> getUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #getUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #post,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> postUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #postUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #postUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #put,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> putUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #putUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #putUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #delete,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> deleteUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #deleteUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #deleteUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #patch,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> patchUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #patchUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #patchUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #head,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  _i11.Future<_i2.HttpClientRequest> headUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #headUrl,
          [url],
        ),
        returnValue:
            _i11.Future<_i2.HttpClientRequest>.value(_FakeHttpClientRequest_1(
          this,
          Invocation.method(
            #headUrl,
            [url],
          ),
        )),
      ) as _i11.Future<_i2.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addCredentials,
          [
            url,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addProxyCredentials,
          [
            host,
            port,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}
